spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
  mvc:
    async:
      request-timeout: -1
simmo:
  app:
    jwtSecret: jwtSimmo.comSecretKey
    jwtExpiration: 86400

    jpa:
      hibernate:
        ddl-auto: create-drop
    server:
      port: ${PORT}
      servlet:
        context-path: /

---
spring:
  profiles: prod
  mvc:
    async:
      request-timeout: -1
  simmo:
    app:
      jwtSecret: jwtSimmo.comSecretKey
      jwtExpiration: 86400

  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: ${PORT}
  servlet:
    context-path: /

